### ISSUE TITLE
Baffling Error

### ISSUE THREAD

**Issue by rbunn80110** [MarkusRosen/pytorch_multi_input_example#2]
This is the end of my output when I run pytorch_lightning_regression.py without changes.

I can't seem to figure out what is wrong or how to fix it.

TEST RESULTS
{'test_loss': tensor(737346.6653, device='cuda:0', dtype=torch.float64)}
--------------------------------------------------------------------------------
Testing: 100%|██████████| 9/9 [00:00<00:00,  9.77it/s]
Finding best initial lr: 100%|██████████| 100/100 [00:54<00:00,  1.82it/s]
Exception ignored in: <function tqdm.__del__ at 0x7fd1db6fa1f0>
Traceback (most recent call last):
  File "/home/bob/anaconda3/envs/fastai/lib/python3.8/site-packages/tqdm/std.py", line 1087, in __del__
  File "/home/bob/anaconda3/envs/fastai/lib/python3.8/site-packages/tqdm/std.py", line 1294, in close
  File "/home/bob/anaconda3/envs/fastai/lib/python3.8/site-packages/tqdm/std.py", line 1472, in display
  File "/home/bob/anaconda3/envs/fastai/lib/python3.8/site-packages/tqdm/std.py", line 1090, in __repr__
  File "/home/bob/anaconda3/envs/fastai/lib/python3.8/site-packages/tqdm/std.py", line 1434, in format_dict
TypeError: cannot unpack non-iterable NoneType object

**Comment by rbunn80110** [comment]
Even when I create a fresh environment and install from requirements.txt I still get the same error.

**Comment by MarkusRosen** [comment]
I'm sorry to reply so late to your question, GitHub didn't notify me...

Me and a few of my students did not seem to get this error, can you maybe post your code as well? Could this maybe help you?
https://stackoverflow.com/questions/53680913/typeerror-cannot-unpack-non-iterable-nonetype-object
